[package]
name = "rating-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "*"
dotenv = "*"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
